[package]
name = "funkin-multiplayer-server"
version = "0.1.0"
authors = ["Daniel Conley <himself@danii.dev>", "WaviestBalloon <_@fur.dev>"]
edition = "2018"

[dependencies]
futures = "0.3"
tokio = {version = "1.3.0", features = ["full"]}
warp = "0.3.0"
